---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/files":
    get:
      summary: Retrieves files
      tags:
      - Files
      security:
      - bearer: []
      responses:
        '200':
          description: ok
    post:
      summary: Creates a file
      tags:
      - Files
      parameters: []
      security:
      - bearer: []
      responses:
        '201':
          description: created
        '422':
          description: invalid request
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: file
        required: true
        description: File to be uploaded
  "/api/login":
    post:
      summary: Create Token
      tags:
      - Login
      parameters: []
      responses:
        '200':
          description: token received
        '401':
          description: unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
                  required:
                  - email
                  - password
              required:
              - user
servers:
- url: http://localhost:3000
  variables: {}
components:
  securitySchemes:
    bearer:
      description: JWT key
      type: bearer
      name: Authorization
      in: header
